# Generated by Django 3.2.7 on 2021-09-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_country_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('name', 'country')},
        ),
    ]
