# Generated by Django 3.2.7 on 2021-09-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_province_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'province')},
        ),
    ]
