# Generated by Django 3.2.7 on 2021-09-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_city_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'city', 'latitude', 'longitude', 'postalCode')},
        ),
    ]
