# Generated by Django 3.2.7 on 2021-09-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_address_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('name', 'address', 'categories', 'websites')},
        ),
    ]
